# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:  
#           steps:
#             - run: cd curriculum
#             - run: npm install
#             - run: npm test
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.14.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
            - run: cd curriculum && npm install
            - run: cd curriculum && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
